[package]
name = "music-player"
version = "1.2.0"
edition = "2024"
description = "A terminal music library player"
license = "MIT"
readme = "README.md"
repository = "https://github.com/HZ-TYZQ/tui-music-player"
homepage = "https://github.com/HZ-TYZQ/tui-music-player"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29.0"
dirs = "6.0.0"
lofty = "0.25.1"
nucleo = "0.5.0"
ratatui = "0.30.2"
rodio = { version = "0.22.2", features = ["symphonia-aiff"] }
rusqlite = { version = "0.40.2", features = ["bundled-windows"] }
rustfft = "6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.1.4"
unicode-width = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
async-io = "2"
mpris-server = "0.10"
pollster = "0.4"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = [
    "Foundation",
    "Media",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_WinRT",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
tempfile = "3.27.0"
