[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)] [string] $ProjectDir,
    [Parameter(Mandatory = $true)] [string] $RuntimeDir,
    [Parameter(Mandatory = $true)] [string] $MusicPlayerExe,
    [Parameter(Mandatory = $true)] [string] $Version,
    [Parameter(Mandatory = $true)] [string] $OutputDir
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$project = [System.IO.Path]::GetFullPath($ProjectDir)
$runtime = [System.IO.Path]::GetFullPath($RuntimeDir)
$executable = [System.IO.Path]::GetFullPath($MusicPlayerExe)
$output = [System.IO.Path]::GetFullPath($OutputDir)
$temporaryRoot = if ($env:RUNNER_TEMP) { $env:RUNNER_TEMP } else { $env:TEMP }
$packageName = "music-player-$Version-windows-x86_64"
$stageRoot = Join-Path $temporaryRoot $packageName

foreach ($required in @(
    $runtime,
    $executable,
    (Join-Path $runtime "bin\gst-inspect-1.0.exe"),
    (Join-Path $runtime "lib\gstreamer-1.0"),
    (Join-Path $project "assets\icons\music-player.ico"),
    (Join-Path $project "packaging\windows\ChineseSimplified.isl")
)) {
    if (-not (Test-Path -LiteralPath $required)) {
        throw "Required packaging input was not found: $required"
    }
}

# The official GStreamer installer only presents license text in its setup
# wizard; it does not install license files into the runtime directory.
# LGPL redistribution compliance is therefore satisfied by shipping the
# license material vendored in this repository together with the written
# source-code offer, not by requiring files inside the runtime itself.
# Must match $gstreamerVersion in install-gstreamer.ps1.
$gstreamerVersion = "1.28.6"
$gstreamerLicenseName = "gstreamer-$gstreamerVersion-license.txt"
$thirdPartyLicenses = Join-Path $project "packaging\windows\licenses"
$licenseMaterial = @(
    @{
        Source = Join-Path $thirdPartyLicenses $gstreamerLicenseName
        Sha256 = "f51aa9a8dfb17946d14fee32d17045adee466a82b97beedc6c2f47d0f13ad5b0"
    },
    @{
        Source = Join-Path $thirdPartyLicenses "LGPL-2.1.txt"
        Sha256 = "20e50fe7aae3e56378ebf0417d9de904f55a0e61e4df315333e632a4d3555d95"
    },
    @{
        Source = Join-Path $project "packaging\windows\SOURCE-CODE-OFFER.txt"
        Sha256 = $null
    }
)
foreach ($item in $licenseMaterial) {
    if (-not (Test-Path -LiteralPath $item.Source)) {
        throw "Required license material was not found: $($item.Source)"
    }
    if ($item.Sha256) {
        $actualSha256 = (Get-FileHash -LiteralPath $item.Source -Algorithm SHA256).Hash.ToLowerInvariant()
        if ($actualSha256 -ne $item.Sha256) {
            throw "License material SHA-256 mismatch for $($item.Source): expected $($item.Sha256), got $actualSha256"
        }
    }
}

if (Test-Path -LiteralPath $stageRoot) {
    Remove-Item -LiteralPath $stageRoot -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $stageRoot | Out-Null
Copy-Item -Path (Join-Path $runtime "*") -Destination $stageRoot -Recurse -Force

# The GStreamer runtime is produced by running GStreamer's own Inno Setup
# installer, which leaves its uninstaller metadata (unins*.exe/.dat/.msg)
# behind in the runtime root. Those files belong to the GStreamer installer
# (built with Inno Setup 6.7.0) and would clash with this package's own
# uninstaller data built by a different Inno Setup version, so they must
# never enter the staged package (nor the Portable ZIP / Installer built
# from it). Music Player's own uninstaller is generated by its installer on
# the user's machine and is not part of the stage.
Get-ChildItem -LiteralPath $stageRoot -Recurse -File |
    Where-Object { $_.Name -match '^unins\d*\.(exe|dat|msg)$' } |
    Remove-Item -Force

$stageBin = Join-Path $stageRoot "bin"
Copy-Item -LiteralPath $executable -Destination (Join-Path $stageBin "music-player.exe") -Force
Copy-Item -LiteralPath (Join-Path $project "packaging\windows\music-player.cmd") -Destination $stageRoot
Copy-Item -LiteralPath (Join-Path $project "packaging\windows\README-Windows.txt") -Destination $stageRoot
Copy-Item -LiteralPath (Join-Path $project "packaging\windows\THIRD-PARTY-NOTICES.txt") -Destination $stageRoot
Copy-Item -LiteralPath (Join-Path $project "assets\icons\music-player.ico") -Destination $stageRoot
Copy-Item -LiteralPath (Join-Path $project "LICENSE") -Destination $stageRoot

$stageLicenses = Join-Path $stageRoot "third-party-licenses"
New-Item -ItemType Directory -Force -Path $stageLicenses | Out-Null
Copy-Item -LiteralPath (Join-Path $thirdPartyLicenses $gstreamerLicenseName) -Destination $stageLicenses
Copy-Item -LiteralPath (Join-Path $thirdPartyLicenses "LGPL-2.1.txt") -Destination $stageLicenses
Copy-Item -LiteralPath (Join-Path $project "packaging\windows\SOURCE-CODE-OFFER.txt") -Destination $stageRoot

foreach ($required in @(
    (Join-Path $stageRoot "LICENSE"),
    (Join-Path $stageRoot "THIRD-PARTY-NOTICES.txt"),
    (Join-Path $stageRoot "SOURCE-CODE-OFFER.txt"),
    (Join-Path $stageLicenses $gstreamerLicenseName),
    (Join-Path $stageLicenses "LGPL-2.1.txt")
)) {
    if (-not (Test-Path -LiteralPath $required)) {
        throw "Staged package is missing required license material: $required"
    }
}

$foreignUninstallers = Get-ChildItem -LiteralPath $stageRoot -Recurse -File |
    Where-Object { $_.Name -match '^unins\d*\.(exe|dat|msg)$' }
if ($foreignUninstallers) {
    throw "Staged package must not contain foreign uninstaller metadata: $($foreignUninstallers.FullName -join ', ')"
}

$oldPath = $env:PATH
$oldPluginSystemPath = $env:GST_PLUGIN_SYSTEM_PATH_1_0
$oldPluginPath = $env:GST_PLUGIN_PATH_1_0
try {
    $env:PATH = "$stageBin;$oldPath"
    $env:GST_PLUGIN_SYSTEM_PATH_1_0 = Join-Path $stageRoot "lib\gstreamer-1.0"
    $env:GST_PLUGIN_PATH_1_0 = ""
    $inspect = Join-Path $stageBin "gst-inspect-1.0.exe"
    foreach ($feature in @("playbin3", "decodebin3", "spectrum", "fakesink", "autoaudiosink")) {
        & $inspect $feature *> $null
        if ($LASTEXITCODE -ne 0) {
            throw "Packaged GStreamer runtime is missing feature: $feature"
        }
    }
    & (Join-Path $stageRoot "music-player.cmd") --version
    if ($LASTEXITCODE -ne 0) {
        throw "Packaged music-player launcher failed with exit code $LASTEXITCODE"
    }
}
finally {
    $env:PATH = $oldPath
    $env:GST_PLUGIN_SYSTEM_PATH_1_0 = $oldPluginSystemPath
    $env:GST_PLUGIN_PATH_1_0 = $oldPluginPath
}

New-Item -ItemType Directory -Force -Path $output | Out-Null
$portableZip = Join-Path $output "$packageName-portable.zip"
if (Test-Path -LiteralPath $portableZip) {
    Remove-Item -LiteralPath $portableZip -Force
}
Compress-Archive -LiteralPath $stageRoot -DestinationPath $portableZip -CompressionLevel Optimal

$isccCommand = Get-Command "ISCC.exe" -ErrorAction SilentlyContinue
$iscc = if ($isccCommand) { $isccCommand.Source } else { $null }
if (-not $iscc) {
    $fallback = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
    if (Test-Path -LiteralPath $fallback) {
        $iscc = $fallback
    } else {
        throw "ISCC.exe was not found"
    }
}

$installerScript = Join-Path $project "packaging\windows\music-player.iss"
& $iscc "/DAppVersion=$Version" "/DStageDir=$stageRoot" "/DOutputDir=$output" $installerScript
if ($LASTEXITCODE -ne 0) {
    throw "Inno Setup compiler exited with code $LASTEXITCODE"
}

$setup = Join-Path $output "$packageName-setup.exe"
if (-not (Test-Path -LiteralPath $setup)) {
    throw "Expected installer was not created: $setup"
}

Write-Host "Windows artifacts:"
Write-Host $portableZip
Write-Host $setup
